apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: staging
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASS: YXJpemtpMjUxOTkx
  DB_NAME: ZGJfbWFjcm9zcw==
  DB_HOST: ZGItbWFjcm9zcy5jaDQwYXBpeHJ0ZjMuYXAtc291dGhlYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=

